/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.hi6484.android.sample.adventcalendarswig;

public class sample_adventJNI {
  public final static native void adventInitValue();
  public final static native void adventAddValue(long jarg1);
  public final static native long adventGetValue();
}
