/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.hi6484.android.sample.adventcalendarswig;

public class sample_advent {
  public static void adventInitValue() {
    sample_adventJNI.adventInitValue();
  }

  public static void adventAddValue(long value) {
    sample_adventJNI.adventAddValue(value);
  }

  public static long adventGetValue() {
    return sample_adventJNI.adventGetValue();
  }

}
